title: Dushyanth Reddy
logo: /Users/dushyanthreddybonthu/Downloads/IMG_2938.png
description: I like to optimize transformers to accelerate LLM inference.
show_downloads: false
remote_theme: pages-themes/midnight@v0.2.0
